In [4]:
import numpy as np

# creation of numpy array

In [3]:
x = np.array([1,2,3,4,5])
print(x)
print(type(x))      #

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
print(x.size)   # total no. of element
print(x.shape)  # dimension wise element
print(x.ndim)   # num of dimension

5
(5,)
1


In [7]:
x2d = np.array([[1,2,3],[5,6,8]])
print(x2d)
print(x2d.size)   # total no. of element
print(x2d.shape)  # dimension wise element
print(x2d.ndim)   # num of dimension

[[1 2 3]
 [5 6 8]]
6
(2, 3)
2


In [11]:
x25 = np.random.randint(1,100,(5,5)) # matrix range 1 to 100
print(x25)

[[37 21 25 38  8]
 [52 15 97 79 21]
 [92 79 97 97 59]
 [37 89 94 71 48]
 [31 70  8 39 96]]


In [15]:
xseq1 = np.arange(1,101, 4)
print("1D Matrix")
print(xseq1)
print(xseq1.size)

print("1D array reshaped to 2d")
print(xseq1.reshape(5,5))

1D Matrix
[ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93
 97]
25
1D array reshaped to 2d
[[ 1  5  9 13 17]
 [21 25 29 33 37]
 [41 45 49 53 57]
 [61 65 69 73 77]
 [81 85 89 93 97]]


In [18]:
xseq2 = np.linspace(1,100,50)
print("1D Matrix")
print(xseq2)
print(xseq2.size)

print("1D array reshaped to 2d")
print(xseq2.reshape(10,5,))


print("1D array reshaped to 3d")
print(xseq2.reshape(5,5,2))

1D Matrix
[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]
50
1D array reshaped to 2d
[[  1.           3.02040816   5.04081633   7.06122449   9.08163265]
 [ 11.10204082  13.12244898  15.14285714  17.16326531  19.18367347]
 [ 21.20408163  23.2244898   25.24489796  27.26530612  29.28571429]
 [ 31.30612245  33.32653061  35.34693878  37.36734694  39.3877551 ]
 [ 41.40816327  43.42857143  45

In [20]:
xseq2d = xseq2.reshape(10,5)
print(xseq2)

[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]


In [21]:
np.ones((5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# indexing and Slicing,boolean filter,maths and stats,method

In [22]:
x25

array([[37, 21, 25, 38,  8],
       [52, 15, 97, 79, 21],
       [92, 79, 97, 97, 59],
       [37, 89, 94, 71, 48],
       [31, 70,  8, 39, 96]])

# to find first row

In [23]:
# first row
print(x25[0])

[37 21 25 38  8]


In [24]:
# last raw
print(x25[-1])

[31 70  8 39 96]


In [26]:
print(x25[0,1]) # for particular element

21


In [29]:
# 1st column
print(x25[:,0])

# 2nd column
print(x25[:,1])

# last column
print(x25[:,-1])

[37 52 92 37 31]
[21 15 79 89 70]
[ 8 21 59 48 96]


In [30]:
# Extracting multiple columns
print(x25[:,[0,1,2]])

# same as above
print(x25[:,:3])

[[37 21 25]
 [52 15 97]
 [92 79 97]
 [37 89 94]
 [31 70  8]]
[[37 21 25]
 [52 15 97]
 [92 79 97]
 [37 89 94]
 [31 70  8]]


In [31]:
print(x25[:4,[0,1]])

[[37 21]
 [52 15]
 [92 79]
 [37 89]]


In [32]:
print(x25)

[[37 21 25 38  8]
 [52 15 97 79 21]
 [92 79 97 97 59]
 [37 89 94 71 48]
 [31 70  8 39 96]]


In [34]:
print(x25[1:,3:])

[[79 21]
 [97 59]
 [71 48]
 [39 96]]


In [39]:
print(x25[:,[0,1,2,3,]])

[[37 21 25 38]
 [52 15 97 79]
 [92 79 97 97]
 [37 89 94 71]
 [31 70  8 39]]


# Boolean Filter

In [40]:
x25

array([[37, 21, 25, 38,  8],
       [52, 15, 97, 79, 21],
       [92, 79, 97, 97, 59],
       [37, 89, 94, 71, 48],
       [31, 70,  8, 39, 96]])

In [45]:
for i in x25:
    for j in i:
        if j <= 20:
         print(j)

8
15
8


In [47]:
x25 <= 20   # boolean filter

array([[False, False, False, False,  True],
       [False,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True, False, False]])

In [48]:
x25[ x25 <= 20]

array([ 8, 15,  8])

In [49]:
x25[ x25 > 50] 

array([52, 97, 79, 92, 79, 97, 97, 59, 89, 94, 71, 70, 96])

In [52]:
(x25 > 20) & (x25 <70)

array([[ True,  True,  True,  True, False],
       [ True, False, False, False,  True],
       [False, False, False, False,  True],
       [ True, False, False, False,  True],
       [ True, False, False,  True, False]])

In [53]:
x25[(x25 > 20) & (x25 <70)]

array([37, 21, 25, 38, 52, 21, 59, 37, 48, 31, 39])

In [59]:
np.append(x25,np.array([[1,2,4,8,6]]),axis=0)

array([[37, 21, 25, 38,  8],
       [52, 15, 97, 79, 21],
       [92, 79, 97, 97, 59],
       [37, 89, 94, 71, 48],
       [31, 70,  8, 39, 96],
       [ 1,  2,  4,  8,  6]])

In [61]:
x25

array([[37, 21, 25, 38,  8],
       [52, 15, 97, 79, 21],
       [92, 79, 97, 97, 59],
       [37, 89, 94, 71, 48],
       [31, 70,  8, 39, 96]])

# Array 2x3 and 3x2

In [63]:
x20 = np.array([[1,2,3],[5,8,7]])

In [64]:
x21 = np.array([[4,5],[7,5],[8,6]])

In [65]:
x21.T

array([[4, 7, 8],
       [5, 5, 6]])

In [68]:
print(np.hstack((x20,x21.T))) # horizontal stack

[[1 2 3 4 7 8]
 [5 8 7 5 5 6]]


In [69]:
print(np.hstack((x21.T,x20)))

[[4 7 8 1 2 3]
 [5 5 6 5 8 7]]


In [70]:
print(np.vstack((x20,x21.T))) #vertical stack
print(np.vstack((x20.T,x21)))

[[1 2 3]
 [5 8 7]
 [4 7 8]
 [5 5 6]]
[[1 5]
 [2 8]
 [3 7]
 [4 5]
 [7 5]
 [8 6]]


In [5]:
x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,(3,3))
print(x)
print()
print(y)


[[1 6 1]
 [8 6 7]
 [7 4 4]]

[[8 9 8]
 [5 2 2]
 [6 7 6]]


In [6]:
print('add')
print(x+y)
print('subtract')
print(x-y)
print('divide')
print(x/y)
print('mod')
print(x%y)

add
[[ 9 15  9]
 [13  8  9]
 [13 11 10]]
subtract
[[-7 -3 -7]
 [ 3  4  5]
 [ 1 -3 -2]]
divide
[[0.125      0.66666667 0.125     ]
 [1.6        3.         3.5       ]
 [1.16666667 0.57142857 0.66666667]]
mod
[[1 6 1]
 [3 0 1]
 [1 4 4]]


In [7]:
x.sum()

44

In [9]:
x.sum(axis=0)# row wise

array([16, 16, 12])

In [10]:
x.sum(axis=1)# colm wise

array([ 8, 21, 15])

In [11]:
print(x.mean())
print(x.mean(axis=0))
print(x.mean(axis=1))

4.888888888888889
[5.33333333 5.33333333 4.        ]
[2.66666667 7.         5.        ]


In [16]:
print(x.max()) # min value
print(x.min()) #max value
print(x.argmax()) # index of max value
print(x.argmin()) # index of min value
print(x.flatten()[4]) # accessing the index value given by argument


8
1
3
0
6


In [15]:
np.median(x)# some fn are colled using np,if not avaliable through the variable

6.0